name: dk_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^3.13.0  # Ensure correct version
  firebase_auth: ^5.5.2   # Ensure correct version
  
  # Social login packages
  google_sign_in: ^6.3.0   # Ensure correct version
  logger: ^1.0.0 # Add this line for logging
  flutter_facebook_auth: ^6.0.4  # Ensure correct version

  # UI and additional utility packages
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
