// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9pjmVZxq9ZsOowfWijLe2I4JAIuQFQXA',
    appId: '1:392847418626:web:05de22d01deb2b4b94ce1b',
    messagingSenderId: '392847418626',
    projectId: 'dkapp-2025',
    authDomain: 'dkapp-2025.firebaseapp.com',
    storageBucket: 'dkapp-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh0EjPRnfu60MzZcTUIaCo8KrJcks_5Do',
    appId: '1:392847418626:android:5fd12040274671cc94ce1b',
    messagingSenderId: '392847418626',
    projectId: 'dkapp-2025',
    storageBucket: 'dkapp-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGaEO-0OWhNHt0Pv49mQfzCp_gTPYEgTw',
    appId: '1:392847418626:ios:a1b09932345f726194ce1b',
    messagingSenderId: '392847418626',
    projectId: 'dkapp-2025',
    storageBucket: 'dkapp-2025.firebasestorage.app',
    iosBundleId: 'com.example.dkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGaEO-0OWhNHt0Pv49mQfzCp_gTPYEgTw',
    appId: '1:392847418626:ios:a1b09932345f726194ce1b',
    messagingSenderId: '392847418626',
    projectId: 'dkapp-2025',
    storageBucket: 'dkapp-2025.firebasestorage.app',
    iosBundleId: 'com.example.dkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9pjmVZxq9ZsOowfWijLe2I4JAIuQFQXA',
    appId: '1:392847418626:web:1c0882c0283dc3e394ce1b',
    messagingSenderId: '392847418626',
    projectId: 'dkapp-2025',
    authDomain: 'dkapp-2025.firebaseapp.com',
    storageBucket: 'dkapp-2025.firebasestorage.app',
  );
}
